/**
 * types/telemetry.ts
 * ─────────────────────────────────────────────────────────────────
 * Core data interfaces for the FarmAssist IoT Dashboard.
 *
 * These types model the shapes stored in Firebase Realtime Database by the ESP
 * microcontroller and consumed by the React dashboard.
 *
 * RTDB path: sensor
 * ─────────────────────────────────────────────────────────────────
 */

/** Live sensor telemetry pushed by the ESP microcontroller. */
export interface SensorTelemetry {
  /** Air temperature in °C */
  temperature: number;
  /** Soil moisture in % */
  moisture: number;
  /** Water reservoir level in % */
  waterLevel: number;
  /** Light intensity in lux */
  light: number;
  /** Unix epoch (ms) — generated client-side since RTDB has no timestamp */
  timestamp: number;
}

/** Metadata describing the device sending telemetry. */
export interface DeviceMeta {
  id: string;
  name: string;
  lastSeen: number;
}

/** A single point on the live telemetry chart. */
export interface ChartDataPoint {
  /** Unix timestamp in ms (used as the X axis) */
  timestamp: number;
  /** The metric value for this snapshot */
  value: number;
  /** Individual sensor values for per-sensor chart selection */
  temperature?: number;
  moisture?: number;
  waterLevel?: number;
  light?: number;
}

/**
 * A persisted graph snapshot saved to the `graph_history` collection.
 * Used to retain historical chart data across page refreshes.
 */
export interface GraphSnapshot {
  /** Auto-generated Firestore document ID */
  id: string;
  /** Which sensor metric this snapshot represents */
  metricType: SensorKey;
  /** Ordered array of data points */
  dataPoints: ChartDataPoint[];
  /** Unix epoch (ms) when the snapshot was created */
  createdAt: number;
}

/** Union of all sensor metric keys — used for type-safe lookups. */
export type SensorKey = "temperature" | "moisture" | "waterLevel" | "light";

/** Display metadata for each sensor metric. */
export interface SensorMeta {
  label: string;
  unit: string;
  icon: string; // Lucide icon name
  color: string; // Tailwind color class (for charts)
  hexColor: string; // Raw hex for Recharts stroke
  min: number;
  max: number;
  optimalRange: [number, number];
}

/** Map of sensor keys to their display metadata. */
export const SENSOR_META: Record<SensorKey, SensorMeta> = {
  temperature: {
    label: "Temperature",
    unit: "°C",
    icon: "Thermometer",
    color: "text-orange-500",
    hexColor: "#f97316",
    min: 0,
    max: 60,
    optimalRange: [18, 30],
  },
  moisture: {
    label: "Soil Moisture",
    unit: "%",
    icon: "Sprout",
    color: "text-emerald-500",
    hexColor: "#10b981",
    min: 0,
    max: 100,
    optimalRange: [30, 60],
  },
  waterLevel: {
    label: "Water Level",
    unit: "%",
    icon: "Waves",
    color: "text-cyan-500",
    hexColor: "#06b6d4",
    min: 0,
    max: 100,
    optimalRange: [20, 90],
  },
  light: {
    label: "Light",
    unit: "lux",
    icon: "Sun",
    color: "text-yellow-500",
    hexColor: "#eab308",
    min: 0,
    max: 10000,
    optimalRange: [1000, 8000],
  },
};

/** Connection status of the hardware node. */
export type ConnectionStatus = "live" | "stale" | "offline";

/** A recommendation generated by the heuristic engine. */
export interface Recommendation {
  id: string;
  severity: "info" | "warning" | "critical";
  sensor: SensorKey;
  message: string;
  icon: string;
}

/** Rolling history buffer max size. */
export const MAX_HISTORY_SIZE = 200;

/** Maximum graph history records to retain in RTDB. */
export const MAX_GRAPH_HISTORY = 500;

/** Pruning threshold — start deleting when entries exceed this. */
export const PRUNE_THRESHOLD = 300;

/**
 * Allow a few missed ESP32 samples (normally sent every 5 seconds) before
 * showing "Not Responding". A device becomes offline after three times this.
 */
export const DEFAULT_STALE_THRESHOLD_MS = 20_000;
