/**
 * types/telemetry.ts
 * ─────────────────────────────────────────────────────────────────
 * Core data interfaces for the FarmAssist IoT Dashboard.
 *
 * These types model the shapes stored in Firebase Realtime Database by the ESP
 * microcontroller and consumed by the React dashboard.
 *
 * RTDB paths:
 *   • sensors/latest            — live sensor readings
 *   • sensors/history/{metric}  — persisted chart snapshots
 * ─────────────────────────────────────────────────────────────────
 */

/** Live sensor telemetry pushed by the ESP microcontroller. */
export interface SensorTelemetry {
  /** Air temperature in °C */
  temperature: number;
  /** Relative air humidity in % */
  humidity: number;
  /** Soil moisture in % */
  moisture: number;
  /** Water reservoir level in % */
  waterLevel: number;
  /** Unix epoch (ms) when the reading was taken */
  timestamp: number;
}

/** Metadata describing the device sending telemetry. */
export interface DeviceMeta {
  id: string;
  name: string;
  lastSeen: number;
}

/** A single point on the live telemetry chart. */
export interface ChartDataPoint {
  /** Unix timestamp in ms (used as the X axis) */
  timestamp: number;
  /** The metric value for this snapshot */
  value: number;
}

/**
 * A persisted graph snapshot saved to the `graph_history` collection.
 * Used to retain historical chart data across page refreshes.
 */
export interface GraphSnapshot {
  /** Auto-generated Firestore document ID */
  id: string;
  /** Which sensor metric this snapshot represents */
  metricType: SensorKey;
  /** Ordered array of data points */
  dataPoints: ChartDataPoint[];
  /** Unix epoch (ms) when the snapshot was created */
  createdAt: number;
}

/** Union of all sensor metric keys — used for type-safe lookups. */
export type SensorKey = "temperature" | "humidity" | "moisture" | "waterLevel";

/** Display metadata for each sensor metric. */
export interface SensorMeta {
  label: string;
  unit: string;
  icon: string; // Lucide icon name
  color: string; // Tailwind color class (for charts)
  hexColor: string; // Raw hex for Recharts stroke
  min: number;
  max: number;
  optimalRange: [number, number];
}

/** Map of sensor keys to their display metadata. */
export const SENSOR_META: Record<SensorKey, SensorMeta> = {
  temperature: {
    label: "Temperature",
    unit: "°C",
    icon: "Thermometer",
    color: "text-orange-500",
    hexColor: "#f97316",
    min: -10,
    max: 60,
    optimalRange: [18, 30],
  },
  humidity: {
    label: "Air Humidity",
    unit: "%",
    icon: "Droplets",
    color: "text-blue-500",
    hexColor: "#3b82f6",
    min: 0,
    max: 100,
    optimalRange: [40, 70],
  },
  moisture: {
    label: "Soil Moisture",
    unit: "%",
    icon: "Sprout",
    color: "text-emerald-500",
    hexColor: "#10b981",
    min: 0,
    max: 100,
    optimalRange: [30, 60],
  },
  waterLevel: {
    label: "Water Level",
    unit: "%",
    icon: "Waves",
    color: "text-cyan-500",
    hexColor: "#06b6d4",
    min: 0,
    max: 100,
    optimalRange: [20, 90],
  },
};

/** Connection status of the hardware node. */
export type ConnectionStatus = "live" | "stale" | "offline";

/** A recommendation generated by the heuristic engine. */
export interface Recommendation {
  id: string;
  severity: "info" | "warning" | "critical";
  sensor: SensorKey;
  message: string;
  icon: string;
}

/** Rolling history buffer max size. */
export const MAX_HISTORY_SIZE = 15;

/** Maximum graph history records to retain in Firestore. */
export const MAX_GRAPH_HISTORY = 100;

/** Default stale threshold (ms) before a node is considered offline. */
export const DEFAULT_STALE_THRESHOLD_MS = 10_000;
