/**
 * RecommendationPanel.tsx
 * ─────────────────────────────────────────────────────────────────
 * Displays actionable farming recommendations generated by the
 * client-side heuristic rule engine. Updates in real time as new
 * telemetry arrives from Firebase.
 *
 * Severity levels:
 *  • info     — blue/neutral
 *  • warning  — amber
 *  • critical — red, attention-grabbing
 * ─────────────────────────────────────────────────────────────────
 */

"use client";

import {
  AlertTriangle,
  Thermometer,
  Droplets,
  Sprout,
  Waves,
  Wind,
  Snowflake,
  Sun,
  CheckCircle,
  type LucideIcon,
} from "lucide-react";
import type { Recommendation } from "@/types/telemetry";

const ICON_MAP: Record<string, LucideIcon> = {
  AlertTriangle,
  Thermometer,
  Droplets,
  Sprout,
  Waves,
  Wind,
  Snowflake,
  Sun,
};

const SEVERITY_STYLES: Record<
  Recommendation["severity"],
  { bg: string; border: string; icon: string; badge: string }
> = {
  info: {
    bg: "bg-blue-950/30",
    border: "border-blue-800/40",
    icon: "text-blue-400",
    badge: "bg-blue-900/50 text-blue-400",
  },
  warning: {
    bg: "bg-amber-950/30",
    border: "border-amber-800/40",
    icon: "text-amber-400",
    badge: "bg-amber-900/50 text-amber-400",
  },
  critical: {
    bg: "bg-red-950/30",
    border: "border-red-800/40",
    icon: "text-red-400",
    badge: "bg-red-900/50 text-red-400",
  },
};

interface RecommendationPanelProps {
  recommendations: Recommendation[];
}

export default function RecommendationPanel({
  recommendations,
}: RecommendationPanelProps) {
  // Sort: critical first, then warnings, then info
  const sorted = [...recommendations].sort((a, b) => {
    const order = { critical: 0, warning: 1, info: 2 };
    return order[a.severity] - order[b.severity];
  });

  const criticalCount = sorted.filter((r) => r.severity === "critical").length;
  const warningCount = sorted.filter((r) => r.severity === "warning").length;

  return (
    <div className="rounded-2xl border border-cyan-900/20 bg-[#0c1a2e] p-6">
      {/* ── Header ── */}
      <div className="mb-4 flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold text-white">
            AI Recommendations
          </h2>
          <p className="text-sm text-slate-400">
            Real-time analysis of your sensor data
          </p>
        </div>
        <div className="flex gap-2">
          {criticalCount > 0 && (
            <span className="inline-flex items-center gap-1 rounded-full bg-red-900/50 px-2.5 py-0.5 text-xs font-semibold text-red-400">
              {criticalCount} critical
            </span>
          )}
          {warningCount > 0 && (
            <span className="inline-flex items-center gap-1 rounded-full bg-amber-900/50 px-2.5 py-0.5 text-xs font-semibold text-amber-400">
              {warningCount} warning{warningCount !== 1 && "s"}
            </span>
          )}
        </div>
      </div>

      {/* ── Recommendation list ── */}
      {sorted.length > 0 ? (
        <div className="space-y-3">
          {sorted.map((rec) => {
            const styles = SEVERITY_STYLES[rec.severity];
            const Icon = ICON_MAP[rec.icon] ?? AlertTriangle;

            return (
              <div
                key={rec.id}
                className={`flex items-start gap-3 rounded-xl border p-3.5 transition-colors ${styles.bg} ${styles.border}`}
              >
                <Icon className={`mt-0.5 h-5 w-5 shrink-0 ${styles.icon}`} />
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-slate-200">
                    {rec.message}
                  </p>
                </div>
                <span
                  className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${styles.badge}`}
                >
                  {rec.severity}
                </span>
              </div>
            );
          })}
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center py-8">
          <CheckCircle className="mb-2 h-10 w-10 text-emerald-500" />
          <p className="text-sm font-medium text-slate-300">
            All systems nominal
          </p>
          <p className="text-xs text-slate-500">
            No alerts — your farm is looking great!
          </p>
        </div>
      )}
    </div>
  );
}
