/**
 * RecommendationPanel.tsx
 * ─────────────────────────────────────────────────────────────────
 * Displays detailed, AI-style analysis generated by the
 * client-side heuristic rule engine. Each recommendation shows
 * a summary, expandable reasoning, confidence score, and
 * actionable steps. Updates in real time as new telemetry arrives.
 * ─────────────────────────────────────────────────────────────────
 */

"use client";

import { useState } from "react";
import {
  AlertTriangle,
  Thermometer,
  Droplets,
  Sprout,
  Waves,
  Snowflake,
  Sun,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  Sparkles,
  type LucideIcon,
} from "lucide-react";
import type { Recommendation } from "@/types/telemetry";

const ICON_MAP: Record<string, LucideIcon> = {
  AlertTriangle,
  Thermometer,
  Droplets,
  Sprout,
  Waves,
  Snowflake,
  Sun,
};

const SEVERITY_STYLES: Record<
  Recommendation["severity"],
  { bg: string; border: string; icon: string; badge: string; glow: string }
> = {
  info: {
    bg: "bg-blue-950/30",
    border: "border-blue-800/40",
    icon: "text-blue-400",
    badge: "bg-blue-900/50 text-blue-400",
    glow: "shadow-blue-500/5",
  },
  warning: {
    bg: "bg-amber-950/30",
    border: "border-amber-800/40",
    icon: "text-amber-400",
    badge: "bg-amber-900/50 text-amber-400",
    glow: "shadow-amber-500/5",
  },
  critical: {
    bg: "bg-red-950/30",
    border: "border-red-800/40",
    icon: "text-red-400",
    badge: "bg-red-900/50 text-red-400",
    glow: "shadow-red-500/10",
  },
};

/* ── Confidence badge ──────────────────────────────────────── */

function ConfidenceBadge({ confidence }: { confidence: number }) {
  const color =
    confidence >= 90
      ? "text-emerald-400"
      : confidence >= 75
        ? "text-cyan-400"
        : "text-amber-400";
  const bg =
    confidence >= 90
      ? "bg-emerald-500/15"
      : confidence >= 75
        ? "bg-cyan-500/15"
        : "bg-amber-500/15";

  return (
    <span
      className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold ${bg} ${color}`}
    >
      <Sparkles className="h-2.5 w-2.5" />
      {confidence}% confidence
    </span>
  );
}

/* ── Expandable recommendation card ────────────────────────── */

interface RecommendationCardProps {
  rec: Recommendation;
  defaultExpanded?: boolean;
}

function RecommendationCard({
  rec,
  defaultExpanded = false,
}: RecommendationCardProps) {
  const [expanded, setExpanded] = useState(defaultExpanded);
  const styles = SEVERITY_STYLES[rec.severity];
  const Icon = ICON_MAP[rec.icon] ?? AlertTriangle;

  return (
    <div
      className={`rounded-xl border p-4 transition-all ${styles.bg} ${styles.border} shadow-lg ${styles.glow} ${
        expanded ? "ring-1 ring-white/5" : ""
      }`}
    >
      {/* ── Header row ── */}
      <div className="flex items-start gap-3">
        <Icon className={`mt-0.5 h-5 w-5 shrink-0 ${styles.icon}`} />
        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            <p className="text-sm font-medium text-slate-200">{rec.message}</p>
          </div>
          <div className="mt-1.5 flex flex-wrap items-center gap-2">
            <span
              className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${styles.badge}`}
            >
              {rec.severity}
            </span>
            {rec.confidence !== undefined && (
              <ConfidenceBadge confidence={rec.confidence} />
            )}
          </div>
        </div>
        {rec.analysis && (
          <button
            type="button"
            onClick={() => setExpanded(!expanded)}
            className="shrink-0 rounded-lg p-1.5 text-slate-500 transition-colors hover:bg-white/5 hover:text-slate-300"
            aria-label={expanded ? "Collapse analysis" : "Expand analysis"}
          >
            {expanded ? (
              <ChevronDown className="h-4 w-4" />
            ) : (
              <ChevronRight className="h-4 w-4" />
            )}
          </button>
        )}
      </div>

      {/* ── Expanded analysis ── */}
      {expanded && rec.analysis && (
        <div className="mt-3 ml-8 space-y-3 animate-fade-in">
          {/* AI reasoning */}
          <div className="rounded-lg bg-white/[0.03] p-3">
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1.5">
              Analysis
            </p>
            <p className="text-xs leading-relaxed text-slate-300">
              {rec.analysis}
            </p>
          </div>

          {/* Action steps */}
          {rec.actionSteps && rec.actionSteps.length > 0 && (
            <div className="rounded-lg bg-white/[0.03] p-3">
              <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-2">
                Recommended Actions
              </p>
              <ul className="space-y-1.5">
                {rec.actionSteps.map((step, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-slate-300">
                    <span className="mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-cyan-500/20 text-[9px] font-bold text-cyan-400">
                      {i + 1}
                    </span>
                    <span className="leading-relaxed">{step}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

/* ── Main panel ────────────────────────────────────────────── */

interface RecommendationPanelProps {
  recommendations: Recommendation[];
}

export default function RecommendationPanel({
  recommendations,
}: RecommendationPanelProps) {
  // Sort: critical first, then warnings, then info
  const sorted = [...recommendations].sort((a, b) => {
    const order = { critical: 0, warning: 1, info: 2 };
    return order[a.severity] - order[b.severity];
  });

  const criticalCount = sorted.filter((r) => r.severity === "critical").length;
  const warningCount = sorted.filter((r) => r.severity === "warning").length;
  const avgConfidence =
    sorted.length > 0
      ? Math.round(
          sorted.reduce((acc, r) => acc + (r.confidence ?? 0), 0) /
            sorted.length
        )
      : 0;

  return (
    <div className="rounded-2xl border border-cyan-900/20 bg-[#0c1a2e] p-6">
      {/* ── Header ── */}
      <div className="mb-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-cyan-500/15">
            <Sparkles className="h-4 w-4 text-cyan-400" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-white">Sensor Analysis</h2>
            <p className="text-sm text-slate-400">
              Detailed sensor analysis & recommendations
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {criticalCount > 0 && (
            <span className="inline-flex items-center gap-1 rounded-full bg-red-900/50 px-2.5 py-0.5 text-xs font-semibold text-red-400">
              {criticalCount} critical
            </span>
          )}
          {warningCount > 0 && (
            <span className="inline-flex items-center gap-1 rounded-full bg-amber-900/50 px-2.5 py-0.5 text-xs font-semibold text-amber-400">
              {warningCount} warning{warningCount !== 1 && "s"}
            </span>
          )}
        </div>
      </div>

      {/* ── Confidence summary bar ── */}
      {sorted.length > 0 && (
        <div className="mb-4 flex items-center gap-3 rounded-xl bg-white/[0.03] px-4 py-2.5">
          <div className="flex items-center gap-1.5">
            <Sparkles className="h-3.5 w-3.5 text-cyan-400" />
            <span className="text-xs font-medium text-slate-400">
              Analysis confidence
            </span>
          </div>
          <div className="flex-1">
            <div className="h-1.5 overflow-hidden rounded-full bg-white/5">
              <div
                className="h-full rounded-full bg-gradient-to-r from-cyan-500 to-emerald-400 transition-all duration-700 ease-out"
                style={{ width: `${avgConfidence}%` }}
              />
            </div>
          </div>
          <span className="text-xs font-bold text-cyan-400">
            {avgConfidence}%
          </span>
        </div>
      )}

      {/* ── Recommendation list ── */}
      {sorted.length > 0 ? (
        <div className="space-y-3">
          {sorted.map((rec, index) => (
            <RecommendationCard
              key={rec.id}
              rec={rec}
              defaultExpanded={rec.severity === "critical" || index === 0}
            />
          ))}
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center py-8">
          <CheckCircle className="mb-2 h-10 w-10 text-emerald-500" />
          <p className="text-sm font-medium text-slate-300">
            All systems nominal
          </p>
          <p className="text-xs text-slate-500">
            All sensors are operating within optimal parameters
          </p>
        </div>
      )}

      {/* ── Footer ── */}
      {sorted.length > 0 && (
        <div className="mt-4 flex items-center justify-between border-t border-cyan-900/20 pt-3">
          <p className="text-[10px] text-slate-600">
            Analysis based on real-time telemetry against agronomy best-practice
            thresholds
          </p>
          <p className="text-[10px] text-slate-600">
            {sorted.length} finding{sorted.length !== 1 && "s"}
          </p>
        </div>
      )}
    </div>
  );
}
